service: web-monitoring

provider:
  name: aws
  runtime: nodejs6.10
  region: ${file(./config.js):region}
  stage: ${file(./config.js):stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"
  environment:
    STAGE: ${file(./config.js):stage}
    REGION: ${file(./config.js):region}

functions:
  requestUrl:
    handler: handler.requestUrl
    description: Requests the received url and check if it has received content within
  scrape:
    handler: handler.scrape
    description: Iterate over a list urls at a set interval, defined on the schedule rate
    events:
      - schedule: ${file(./config.js):rate}